
package it.eng.la.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreatePDFService", targetNamespace = "http://it.eng.la.livecyclews/", wsdlLocation = "CreatePDFService.wsdl")
public class CreatePDFService
    extends Service
{

    private final static URL CREATEPDFSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREATEPDFSERVICE_EXCEPTION;
    private final static QName CREATEPDFSERVICE_QNAME = new QName("http://it.eng.la.livecyclews/", "CreatePDFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	 URL baseUrl;
             baseUrl = it.eng.la.ws.CreatePDFService.class.getResource(".");
             url = new URL(baseUrl, "CreatePDFService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREATEPDFSERVICE_WSDL_LOCATION = url;
        CREATEPDFSERVICE_EXCEPTION = e;
    }

    public CreatePDFService() {
        super(__getWsdlLocation(), CREATEPDFSERVICE_QNAME);
    }

    public CreatePDFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREATEPDFSERVICE_QNAME, features);
    }

    public CreatePDFService(URL wsdlLocation) {
        super(wsdlLocation, CREATEPDFSERVICE_QNAME);
    }

    public CreatePDFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREATEPDFSERVICE_QNAME, features);
    }

    public CreatePDFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreatePDFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreatePDFImpl
     */
    @WebEndpoint(name = "CreatePDFPort")
    public CreatePDFImpl getCreatePDFPort() {
        return super.getPort(new QName("http://it.eng.la.livecyclews/", "CreatePDFPort"), CreatePDFImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreatePDFImpl
     */
    @WebEndpoint(name = "CreatePDFPort")
    public CreatePDFImpl getCreatePDFPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://it.eng.la.livecyclews/", "CreatePDFPort"), CreatePDFImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREATEPDFSERVICE_EXCEPTION!= null) {
            throw CREATEPDFSERVICE_EXCEPTION;
        }
        return CREATEPDFSERVICE_WSDL_LOCATION;
    }

}
