
package it.eng.la.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "inserisciCorredoContabile", targetNamespace = "http://xmlns.example.com/1467032449466", wsdlLocation = "inserisciCorredoContabileLA_LS_OK.wsdl")
public class InserisciCorredoContabile_Service
    extends Service
{

    private final static URL INSERISCICORREDOCONTABILE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.eng.la.ws.InserisciCorredoContabile_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.eng.la.ws.InserisciCorredoContabile_Service.class.getResource(".");
            url = new URL(baseUrl, "inserisciCorredoContabileLA_LS_OK.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'inserisciCorredoContabileLA_LS_OK.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INSERISCICORREDOCONTABILE_WSDL_LOCATION = url;
    }

    public InserisciCorredoContabile_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InserisciCorredoContabile_Service() {
        super(INSERISCICORREDOCONTABILE_WSDL_LOCATION, new QName("http://xmlns.example.com/1467032449466", "inserisciCorredoContabile"));
    }

    /**
     * 
     * @return
     *     returns LegalWS
     */
    @WebEndpoint(name = "LegalWSEndpoint1")
    public LegalWS getLegalWSEndpoint1() {
        return super.getPort(new QName("http://xmlns.example.com/1467032449466", "LegalWSEndpoint1"), LegalWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LegalWS
     */
    @WebEndpoint(name = "LegalWSEndpoint1")
    public LegalWS getLegalWSEndpoint1(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.example.com/1467032449466", "LegalWSEndpoint1"), LegalWS.class, features);
    }

}
