
package it.eng.la.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LegalWS", targetNamespace = "http://webservices.servlet.web.snam.lucystar.idoq.it/", wsdlLocation = "LegalWS.WSDL")
public class LegalWS_Service
    extends Service
{

    private final static URL LEGALWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.eng.la.ws.LegalWS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = it.eng.la.ws.LegalWS_Service.class.getResource(".");
            url = new URL(baseUrl, "LegalWS.WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'LegalWS.WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LEGALWS_WSDL_LOCATION = url;
    }

    public LegalWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LegalWS_Service() {
        super(LEGALWS_WSDL_LOCATION, new QName("http://webservices.servlet.web.snam.lucystar.idoq.it/", "LegalWS"));
    }

    /**
     * 
     * @return
     *     returns LegalWS
     */
    @WebEndpoint(name = "LegalWSPort")
    public LegalWS getLegalWSPort() {
        return super.getPort(new QName("http://webservices.servlet.web.snam.lucystar.idoq.it/", "LegalWSPort"), LegalWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LegalWS
     */
    @WebEndpoint(name = "LegalWSPort")
    public LegalWS getLegalWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.servlet.web.snam.lucystar.idoq.it/", "LegalWSPort"), LegalWS.class, features);
    }

}
